version: "3.1"

services:
  sandbox-liquibase:
    container_name: sandbox-liquibase
    image: liquibase/liquibase
    command: --defaultsFile=liquibase.properties rollback v_1-blank-database
    volumes:
      - ./config/changelog.xml:/liquibase/changelog.xml
      - ./scripts:/liquibase/scripts
      - ./config/liquibase.properties:/liquibase/liquibase.properties
    networks:
      - sandbox-database-net
networks:
  sandbox-database-net: